/**
 * Contains announcements shown to the users
 * in the UI for e.g. an upcoming deployment etc.
 */

create table ui.announcement (
    ID					integer generated by default as identity primary key,
    title				varchar(100) null,
    description			varchar(350) null,
    severity			smallint not null default 0,
    display_from_dat	timestamp not null,
    display_to_dat		timestamp not null,
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);