/**
 * One dataset of a beacon at a given time "observe_dat".
 */

create table tree_data.beacon_data (
    ID				integer 			generated by default as identity primary key,
    beacon_id		integer				not null references tree_data.beacon(id),
    humidity		double precision	not null,
    temperature		double precision	not null,
    dew_point		double precision	not null,
    observe_dat		timestamp			not null,
	settings_id		integer				null references tree_data.beacon_settings(id),
    --
    cre_dat			timestamp	not null,
    mod_dat			timestamp	not null,
    cre_usr			varchar(20) not null,
    mod_usr			varchar(20) not null,
	--
	unique (beacon_id, observe_dat)
);