/**
 * Settings of a single beacon at a given time for history logging.
 */

create table tree_data.beacon_settings (
    ID						integer 			generated by default as identity primary key,
    beacon_id				integer				not null references tree_data.beacon(id),
    device_name				varchar(20) 		not null,
    firmware_version_code	integer 			not null,
    transmit_power_db		double precision	not null,
    battery_level			integer 		    not null,
    temperature_units		varchar(1) 		    not null,
    memory_capacity			integer 		    not null,
    ref_time				timestamp 		    null,
    device_id				integer			    not null,
    phys_button_enabled		boolean			    not null,
    temperature_calibration	double precision    not null,
    humidity_calibration	double precision    not null,
    logging_interval_sec	integer			    not null,
    sensor_interval_sec		integer			    not null,
    adv_freq_ms				integer			    not null,
    pin						integer			    not null,
    check_dat				timestamp		    not null,
    --                                          
    cre_dat					timestamp		    not null,
    cre_usr					varchar(20)		    not null,
	--
	unique (beacon_id, check_dat)
);