/**
 * Logging of beacon events.
 */

create table tree_data.beacon_settings (
    ID						integer generated by default as identity primary key,
    "type"					varchar(10) not null,
    message					varchar(200) null,
    --
    cre_dat				timestamp not null,
    cre_usr				varchar(20) not null,
);