/**
 * Settings of a single beacon at a given time for history logging.
 */

create table tree_data.beacon_settings (
    ID						integer generated by default as identity primary key,
    ref_time				timestamp not null,
    logging_interval_min	integer,
    sensor_interval_sec		integer,
    adv_freq_ms				integer,
    transmit_power_db		real,
    firmware_version_code	integer,
    pin						integer,
    check_dat				timestamp,
    --
    cre_dat				timestamp not null,
    cre_usr				varchar(20) not null,
);