/**
 * Logging of beacon events.
 */

create table tree_data.beacon_log (
    ID					integer generated by default as identity primary key,
	beacon_id			integer not null references tree_data.beacon(id),
	severity			varchar(10) not null,
    "type"				varchar(10) not null,
    message				text null,
    event_dat			timestamp not null,
    settings_id			integer null references tree_data.beacon_settings(id),
    --
    cre_dat				timestamp not null,
    cre_usr				varchar(20) not null
);