create table tree_data.city (
    ID				integer generated by default as identity primary key,
    "name"			varchar(50) not null,
    --
    cre_dat			timestamp,
    mod_dat			timestamp,
    cre_usr			varchar(20),
    mod_usr			varchar(20)
);