/**
 * Phenology data for a tree.
 * tree_data.phenology_observation stores all applicable observations.
 */

create table tree_data.phenology (
    ID					integer generated by default as identity primary key,
    tree_id				integer references tree_data.tree(id),
    observer			varchar(200) not null, 			-- name of observing person
    observe_dat			timestamp not null,				-- observation time
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);