/**
 * Phenology data for a tree.
 * tree_data.phenology_observation stores all applicable observations.
 */

create table tree_data.phenology (
    ID					integer generated by default as identity primary key,
    tree_id				integer references tree_data.tree(id),
    observers			varchar(200) null, 										-- name of observing person(s) (only if they are anonymous)
	observers_ref		integer null references application.user_ref(ref_id),	-- ref to observing users (only if not anonymous)
    observe_dat			timestamp not null,										-- observation time
	user_remark			varchar(350) null,										-- users' additional remarks	
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null,
	--
	unique (tree_id, observe_dat)
);