/**
 * Defines observation types.
 * Used to check which results are eligible for a specific object.
 * This could be "Buds", "Fruits" etc.
 * 
 * This should not contain a specific object, but rather a TYPE of object.
 */

create table tree_data.phenology_observation_type (
    ID			integer generated by default as identity primary key,
    "name"		varchar(50) not null,
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);