create table tree_data.tree_location (
    ID				integer generated by default as identity primary key,
	coords_x		real not null,
    coords_y		real not null,
    street			varchar(50) not null,
    city_id			integer references tree_data.city(id),
    --
    cre_dat			timestamp not null,
    mod_dat			timestamp not null,
    cre_usr			varchar(20) not null,
    mod_usr			varchar(20) not null
);