create table tree_data.tree (
    ID				integer generated by default as identity primary key,
    location_id		integer not null references tree_data.tree_location(id),
    species_id		integer not null references tree_data.tree_species(id),
    --
    cre_dat			timestamp not null,
    mod_dat			timestamp not null,
    cre_usr			varchar(20) not null,
    mod_usr			varchar(20) not null
);