create table tree_data.tree_location (
    ID				integer generated by default as identity primary key,
    street			varchar(50) not null,
    city_id			integer references city(id),
    --
    cre_dat			timestamp not null,
    mod_dat			timestamp not null,
    cre_usr			varchar(20) not null,
    mod_usr			varchar(20) not null
);