/**
 * Describes the location of a single tree and its coordinates.
 */

create table tree_data.tree_location (
    ID					integer generated by default as identity primary key,
	coords_x			double precision not null,
    coords_y			double precision not null,
    coords_projection	varchar(20) not null default 'EPSG:900913',
    street				varchar(50) not null,
    city_id				integer references tree_data.city(id),
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);