/**
 * Holds relevant application errors.
 */

create table application."event" (
    ID					integer generated by default as identity primary key,
    message				text not null,
    details				text null,
    severity			varchar(10) not null,
    remark				varchar(200) null,
	event_dat			timestamp not null,
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);