/**
 * Holds user reports.
 */

create table application."report" (
    ID					integer generated by default as identity primary key,
    message				text not null,
    event_ref			integer null references application.event(id) on delete set null,
    user_id				integer null,
    auto_create			bool null,
    resolved			bool not null default false,
    remark				varchar(200) null,
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);