/**
 * Used by many application modules to store associated users.
 */

create table application."user_ref" (
	ID					integer generated by default as identity primary key,
    ref_id				integer, -- client is in carge of getting an id from the sequence created below
    user_id				integer not null, -- no foreign key can be used, since users may be deleted
    --
    cre_dat				timestamp not null,
    cre_usr				varchar(20) not null,
	--
	unique (ref_id, user_id)
);

CREATE SEQUENCE application."user_ref_seq";