/**
 * Specifies all available roles for a user to be assigned
 * to via the access_data.user_role table.
 * Used by the REST interface to check access.
 */

create table access_data."role" (
	id							integer generated by default as identity primary key,
    "name"						varchar(20) not null,
    is_active					bool not null default true,
    --
    cre_dat						timestamp not null,
    mod_dat						timestamp not null,
    cre_usr						varchar(20) not null,
    mod_usr						varchar(20) not null
);

create index access_data_role_name_index ON access_data."role"("name");