/**
 * Holds settings in a key-value manner for the
 * api to use.
 */

create table access_data.settings (
    ID							integer generated by default as identity primary key,
    "key"						varchar(50) not null unique,
    "value"						varchar(200) not null,
    --
    cre_dat						timestamp not null,
    mod_dat						timestamp not null,
    cre_usr						varchar(20) not null,
    mod_usr						varchar(20) not null
);