/**
 * Holds authentication info.
 * Right now, only one row per user is allowed, so only one token can be
 * generated at a time. This table is to enable easy upgrade to
 * simultaneous sessions in the future.
 */

create table access_data.user_auth (
    id							bigint generated by default as identity primary key,
    user_id						integer not null unique references access_data."user"(id) on delete cascade,
    secret						text not null,
    cre_dat						timestamp not null
);