/**
 * Users can share permissions with other users.
 * This information is stored in this table.
 */

create table access_data."user_permission" (
    ID							integer generated by default as identity primary key,
    granting_user_id			integer not null references access_data."user"(id) on delete cascade, -- user granting the permission
    receiving_user_id			integer not null references access_data."user"(id) on delete cascade, -- user receiving the parmission
    permission					varchar(50) not null, -- the permission key (application-internal)
    revoke_dat					timestamp null,
    --
    cre_dat						timestamp not null,
    mod_dat						timestamp not null,
    cre_usr						varchar(20) not null,
    mod_usr						varchar(20) not null,
	--
	unique(granting_user_id, receiving_user_id, permission)
);