/**
 * A prespecified list of fixed possible observation types.
 * Used to check which results are eligible for a specific object.
 * This could be "Fruits" etc.
 * 
 * This should not contain a specific object, but rather a TYPE of object.
 */

create table tree_data.phenology_observation_type (
    ID			integer generated by default as identity primary key,
    "type"		varchar(50) not null,
    --
    cre_dat				timestamp,
    mod_dat				timestamp,
    cre_usr				varchar(20),
    mod_usr				varchar(20)
);