/**
 * A prespecified list of fixed possible observation objects.
 * This could be "fruits" etc.
 */

create table tree_data.phenology_observation_object (
    ID			integer generated by default as identity primary key,
    "name"		varchar(50) not null,
    --
    cre_dat				timestamp,
    mod_dat				timestamp,
    cre_usr				varchar(20),
    mod_usr				varchar(20)
);