/**
 * Physiognomy data for a tree.
 */

create table tree_data.physiognomy (
    ID					integer generated by default as identity primary key,
    tree_id				integer references tree_data.tree(id),
    tree_height			integer not null,
    stem_circumference	integer not null,
    crown_start_height	integer not null,
    crown_width			integer not null,
    observe_dat			timestamp,
    --
    cre_dat				timestamp,
    mod_dat				timestamp,
    cre_usr				varchar(20),
    mod_usr				varchar(20)
);