create table tree_data.tree (
    ID				integer generated by default as identity primary key,
    location_id		integer not null references tree_data.tree_location(id),
    species_id		integer not null references tree_data.tree_species(id),
    type_id			integer not null references tree_data.tree_type(id),
    --
    cre_dat			timestamp,
    mod_dat			timestamp,
    cre_usr			varchar(20),
    mod_usr			varchar(20)
);