create table tree_data.tree_location (
    ID				integer generated by default as identity primary key,
    coords_x		real not null,
    coords_y		real not null,
    street			varchar(50) not null,
    city			varchar(50) not null,
    --
    cre_dat			timestamp,
    mod_dat			timestamp,
    cre_usr			varchar(20),
    mod_usr			varchar(20)
);