-- LOCATION TABLE
create table tree_data."location" (
    ID					integer generated by default as identity primary key,
	coords_x			double precision not null,
    coords_y			double precision not null,
    coords_projection	varchar(20) not null default 'EPSG:900913',
    street				varchar(50) not null,
    city_id				integer references tree_data.city(id),
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);

-- COPY LOCATION DATA
insert into tree_data."location"
select id, coords_x, coords_y, coords_projection, street, city_id, cre_dat, mod_dat, cre_usr, mod_usr
from tree_data.tree_location;

-- ALTER TREE CONSTRAINT
alter table tree_data.tree drop constraint tree_location_id_fkey;
alter table tree_data.tree add constraint tree_location_id_fkey foreign key (location_id) references tree_data."location"(ID);

-- UPDATE SEQUENCE
SELECT setval('tree_data.location_id_seq', (SELECT MAX(id) FROM tree_data.tree_location), true);

-- DELETE OLD TABLE
drop table tree_data.tree_location;

-- BEACON TABLE
alter table tree_data.beacon add column location_id	integer null references tree_data.location(id);

update
	tree_data.beacon b
set
	location_id = t.location_id
from
	tree_data.tree t
where
	b.tree_id = t.id;

alter table tree_data.beacon alter column location_id set not null;
alter table tree_data.beacon alter column tree_id drop not null;

-- 
--
--
--
create table tree_data.beacon (
    ID					integer generated by default as identity primary key,
    device_id			varchar(10) not null unique,
    tree_id				integer null references tree_data.tree(id),
    bluetooth_address	varchar(20) not null unique,
    status				varchar(20) not null default 'NEW',
	location_id			integer not null references tree_data.location(id),
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);

create index tree_data_beacon_tree_id_index ON tree_data.beacon(tree_id);

select nextval('tree_data.location_id_seq');

-- reset SEQUENCE!!!!