/**
 * Contains generic content to display in specified places.
 */

create table user_data."content" (
    id					integer generated by default as identity primary key,
	-- CONTENT
	content_id			varchar(50) not null references user_data.content_registry(content_id),
	content_order		integer not null,
	content_title		varchar(200) null,
	content_lang		varchar(5) not null references user_data.content_lang(id),
    "content"			text not null,
	-- STATE
	is_draft			bool not null default false,
	save_dat			timestamp not null,
	history_id			integer null references user_data.content(id),
	-- USER
	user_id				integer null references access_data."user"(id),
	-- APPROVAL
	approve_dat			timestamp null,
	approve_user_id		integer null references access_data."user"(id),
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);

create index user_data_content_content_id_index ON user_data."content"(content_id);
create index user_data_content_history_id_index ON user_data."content"(history_id);