/**
 * Contains access rules for new and existing user content.
 */

create table user_data.content_registry (
    id						integer generated by default as identity primary key,
	-- CONTENT
	content_id				varchar(50) not null,
	-- SETTINGS
	enabled					bool not null default true, -- overrides everything else, disables viewing and editing
	-- ACCESS
	-- permissions for anonymous users
	anon_allow_view			bool not null default false,
	anon_allow_edit			bool not null default false,
	anon_approval_by_role	integer null references access_data.role(id),
	-- default permissions for all roles not overridden in table user_data.content_access_role
	user_allow_view			bool not null default false,
	user_allow_edit			bool not null default false,
	user_approval_by_role	integer null references access_data.role(id),
    --
    cre_dat					timestamp not null,
    mod_dat					timestamp not null,
    cre_usr					varchar(20) not null,
    mod_usr					varchar(20) not null,
    --
    unique (content_id)
);