/**
 * Contains generic content to display in specified places.
 */

create table user_data.content_generic (
    id					integer generated by default as identity primary key,
    content				text not null,
	lang				varchar(5) not null references user_data.content_generic_lang(id),
	tag					varchar(5) null references user_data.content_generic_tag(id),
    --
    cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null
);