/**
 * Specifies access settings for specific roles.
 */

create table user_data.content_access_role (
	id					integer generated by default as identity primary key,
	content_id			varchar(50) not null references user_data.content_registry(content_id),
	role_id				integer references access_data.role(id),
	-- PERMISSIONS
	allow_view			bool not null default false,
	allow_edit			bool not null default false,
	-- APPROVAL
	approval_by_role	integer null references access_data.role(id),
	--
	cre_dat				timestamp not null,
    mod_dat				timestamp not null,
    cre_usr				varchar(20) not null,
    mod_usr				varchar(20) not null,
	--
	unique (content_id, role_id)
);